import streamlit as st
import re
import tldextract
from urllib.parse import urlparse

st.set_page_config(page_title="CyberSafe AI", layout="centered")

st.title("🛡️ CyberSafe AI")
st.caption("Instant Scam / Phishing Detection for Citizens (SMS • Email • URL)")

text = st.text_area("Paste SMS / Email / WhatsApp message or URL here:", height=180)

SUSPICIOUS_TLDS = {"xyz", "top", "tk", "ml", "ga", "cf", "gq", "click", "icu", "pw"}
SUSPICIOUS_WORDS = [
    "urgent", "immediately", "verify", "kyc", "account", "suspended", "blocked",
    "password", "otp", "pin", "bank", "refund", "reward", "prize", "lottery",
    "click", "login", "confirm", "security alert", "update", "payment"
]
BRAND_WORDS = ["sbi", "hdfc", "icici", "axis", "paypal", "amazon", "flipkart", "google", "microsoft"]

def extract_urls(s: str):
    return re.findall(r"(https?://[^\s]+)", s)

def domain_from_any(url_or_host: str):
    raw = url_or_host.strip()
    if "://" not in raw:
        raw2 = "http://" + raw
    else:
        raw2 = raw
    try:
        u = urlparse(raw2)
        host = u.hostname or ""
    except Exception:
        host = ""
    host = host.strip(".")
    ext = tldextract.extract(host)
    if ext.domain and ext.suffix:
        return f"{ext.domain}.{ext.suffix}", ext.suffix
    return host, ext.suffix

def analyze(message: str):
    score = 0
    reasons = []

    low = message.lower()

    # Suspicious words
    hits = [w for w in SUSPICIOUS_WORDS if w in low]
    if hits:
        score += min(35, 5 * len(hits))
        reasons.append(f"Suspicious language detected: {', '.join(hits[:6])}")

    # Urgency patterns
    if re.search(r"\b(urgent|immediately|within \d+ (minutes|hours))\b", low):
        score += 10
        reasons.append("Urgency/pressure pattern")

    # OTP / PIN ask
    if re.search(r"\b(otp|one time password|pin|cvv)\b", low):
        score += 15
        reasons.append("Asking for OTP/PIN/CVV (common fraud pattern)")

    # URLs
    urls = extract_urls(message)
    if urls:
        reasons.append(f"Contains {len(urls)} link(s)")
    else:
        # Sometimes scammers send domain without scheme
        if re.search(r"\b[a-z0-9-]+\.[a-z]{2,}\b", low):
            reasons.append("Possible link/domain present")

    for u in urls[:3]:
        if u.lower().startswith("http://"):
            score += 10
            reasons.append("Insecure link (HTTP)")

        dom, tld = domain_from_any(u)
        if tld in SUSPICIOUS_TLDS:
            score += 20
            reasons.append(f"Suspicious TLD: .{tld}")

        if dom.count("-") >= 2:
            score += 7
            reasons.append("Domain has many hyphens (often used in phishing)")

        # Brand spoof hint
        for b in BRAND_WORDS:
            if b in dom and dom != b and not dom.endswith(b):
                score += 10
                reasons.append(f"Possible brand impersonation: '{b}' in domain")

    # Shortened URL suspicion
    if any(x in low for x in ["bit.ly", "tinyurl", "t.co", "cutt.ly", "rb.gy"]):
        score += 15
        reasons.append("Shortened link detected (hides real destination)")

    # Clamp
    score = max(0, min(100, score))
    return score, reasons

def complaint_template(message: str, score: int, reasons: list):
    return f"""
CYBER FRAUD / SCAM REPORT (Draft)

1) Incident Summary:
User received a suspicious message/link that appears to be a scam/phishing attempt.

2) Message/Content:
{message}

3) Risk Assessment:
Risk Score: {score}/100
Reasons: {", ".join(reasons) if reasons else "N/A"}

4) Recommended Action Taken:
- Did NOT share OTP/password
- Did NOT enter banking details
- Reported the link/message for investigation

5) Requested Action:
Please investigate and block the fraudulent domain/link and take necessary legal action.

(Generated by CyberSafe AI)
""".strip()

col1, col2 = st.columns(2)

if col1.button("🔍 Analyze"):
    if not text.strip():
        st.warning("Please paste a message or link.")
    else:
        score, reasons = analyze(text)

        st.subheader("Result")
        st.metric("Risk Score", f"{score}/100")

        if score >= 70:
            st.error("🚨 High Risk — Likely Scam/Phishing")
        elif score >= 40:
            st.warning("⚠️ Suspicious — Be careful")
        else:
            st.success("✅ Low Risk — looks safer (still be cautious)")

        st.subheader("Why?")
        if reasons:
            for r in reasons:
                st.write("•", r)
        else:
            st.write("No obvious scam indicators found.")

        st.subheader("Recommended Actions")
        st.write("• Do NOT click unknown links")
        st.write("• Never share OTP/PIN/CVV/password")
        st.write("• Verify from official website/app")
        st.write("• Report to cybercrime portal if suspicious")

        st.session_state["last_score"] = score
        st.session_state["last_reasons"] = reasons

if col2.button("📝 Generate Complaint Draft"):
    if not text.strip():
        st.warning("Paste the message first, then generate report.")
    else:
        score = st.session_state.get("last_score", 0)
        reasons = st.session_state.get("last_reasons", [])
        draft = complaint_template(text, score, reasons)
        st.text_area("Copy this complaint draft:", value=draft, height=260)